spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://112.74.44.130:3306/easylinker_v3?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: easylinker
      password: easylinker
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
      use-global-data-source-stat: true
      filter:
        stat:
          log-slow-sql: true
          merge-sql: true


  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

    job-store-type: jdbc
    overwrite-existing-jobs: true
    auto-startup: true
    startup-delay: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.easylinker.quartz.entity